
CREATE TABLE IF NOT EXISTS cart (
	"id" SERIAL PRIMARY KEY,
	"user_id" INT NOT NULL,
	"sku" BIGINT,
	"count" INT NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE("user_id","sku")
);
