version: '3.8'

services:
  metrics-consumer:
    image: akmuhammet/metrics-consumer:hw9
    container_name: metrics-consumer
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    networks:
      - services-network
