// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: stocks/stocks.proto

package stocksapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStockRequest) Reset() {
	*x = AddStockRequest{}
	mi := &file_stocks_stocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockRequest) ProtoMessage() {}

func (x *AddStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockRequest.ProtoReflect.Descriptor instead.
func (*AddStockRequest) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{0}
}

func (x *AddStockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddStockRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *AddStockRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AddStockRequest) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddStockRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type AddStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStockResponse) Reset() {
	*x = AddStockResponse{}
	mi := &file_stocks_stocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockResponse) ProtoMessage() {}

func (x *AddStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockResponse.ProtoReflect.Descriptor instead.
func (*AddStockResponse) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{1}
}

func (x *AddStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockRequest) Reset() {
	*x = DeleteStockRequest{}
	mi := &file_stocks_stocks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockRequest) ProtoMessage() {}

func (x *DeleteStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockRequest.ProtoReflect.Descriptor instead.
func (*DeleteStockRequest) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteStockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteStockRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type DeleteStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockResponse) Reset() {
	*x = DeleteStockResponse{}
	mi := &file_stocks_stocks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockResponse) ProtoMessage() {}

func (x *DeleteStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockResponse.ProtoReflect.Descriptor instead.
func (*DeleteStockResponse) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_stocks_stocks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{4}
}

func (x *StockItem) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *StockItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StockItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StockItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockItem) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListStocksByLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentPage   int64                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStocksByLocationRequest) Reset() {
	*x = ListStocksByLocationRequest{}
	mi := &file_stocks_stocks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStocksByLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStocksByLocationRequest) ProtoMessage() {}

func (x *ListStocksByLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStocksByLocationRequest.ProtoReflect.Descriptor instead.
func (*ListStocksByLocationRequest) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{5}
}

func (x *ListStocksByLocationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListStocksByLocationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListStocksByLocationRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStocksByLocationRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type ListStocksByLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int64                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStocksByLocationResponse) Reset() {
	*x = ListStocksByLocationResponse{}
	mi := &file_stocks_stocks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStocksByLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStocksByLocationResponse) ProtoMessage() {}

func (x *ListStocksByLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStocksByLocationResponse.ProtoReflect.Descriptor instead.
func (*ListStocksByLocationResponse) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{6}
}

func (x *ListStocksByLocationResponse) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListStocksByLocationResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListStocksByLocationResponse) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListStocksByLocationResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_stocks_stocks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *StockItem             `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_stocks_stocks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockResponse) GetStock() *StockItem {
	if x != nil {
		return x.Stock
	}
	return nil
}

var File_stocks_stocks_proto protoreflect.FileDescriptor

const file_stocks_stocks_proto_rawDesc = "" +
	"\n" +
	"\x13stocks/stocks.proto\x12\x06stocks\x1a\x1cgoogle/api/annotations.proto\"\x84\x01\n" +
	"\x0fAddStockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\",\n" +
	"\x10AddStockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\x12DeleteStockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\"/\n" +
	"\x13DeleteStockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8d\x01\n" +
	"\tStockItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\x92\x01\n" +
	"\x1bListStocksByLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x03R\vcurrentPage\"\xaa\x01\n" +
	"\x1cListStocksByLocationResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.stocks.StockItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x03R\n" +
	"pageNumber\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"#\n" +
	"\x0fGetStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\";\n" +
	"\x10GetStockResponse\x12'\n" +
	"\x05stock\x18\x01 \x01(\v2\x11.stocks.StockItemR\x05stock2\xb4\x03\n" +
	"\fStockService\x12Z\n" +
	"\bAddStock\x12\x17.stocks.AddStockRequest\x1a\x18.stocks.AddStockResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/stocks/item/add\x12f\n" +
	"\vDeleteStock\x12\x1a.stocks.DeleteStockRequest\x1a\x1b.stocks.DeleteStockResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/stocks/item/delete\x12\x83\x01\n" +
	"\x14ListStocksByLocation\x12#.stocks.ListStocksByLocationRequest\x1a$.stocks.ListStocksByLocationResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/stocks/list/location\x12Z\n" +
	"\bGetStock\x12\x17.stocks.GetStockRequest\x1a\x18.stocks.GetStockResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/stocks/item/getB!Z\x1fstocks/pkg/api/stocks;stocksapib\x06proto3"

var (
	file_stocks_stocks_proto_rawDescOnce sync.Once
	file_stocks_stocks_proto_rawDescData []byte
)

func file_stocks_stocks_proto_rawDescGZIP() []byte {
	file_stocks_stocks_proto_rawDescOnce.Do(func() {
		file_stocks_stocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stocks_stocks_proto_rawDesc), len(file_stocks_stocks_proto_rawDesc)))
	})
	return file_stocks_stocks_proto_rawDescData
}

var file_stocks_stocks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_stocks_stocks_proto_goTypes = []any{
	(*AddStockRequest)(nil),              // 0: stocks.AddStockRequest
	(*AddStockResponse)(nil),             // 1: stocks.AddStockResponse
	(*DeleteStockRequest)(nil),           // 2: stocks.DeleteStockRequest
	(*DeleteStockResponse)(nil),          // 3: stocks.DeleteStockResponse
	(*StockItem)(nil),                    // 4: stocks.StockItem
	(*ListStocksByLocationRequest)(nil),  // 5: stocks.ListStocksByLocationRequest
	(*ListStocksByLocationResponse)(nil), // 6: stocks.ListStocksByLocationResponse
	(*GetStockRequest)(nil),              // 7: stocks.GetStockRequest
	(*GetStockResponse)(nil),             // 8: stocks.GetStockResponse
}
var file_stocks_stocks_proto_depIdxs = []int32{
	4, // 0: stocks.ListStocksByLocationResponse.items:type_name -> stocks.StockItem
	4, // 1: stocks.GetStockResponse.stock:type_name -> stocks.StockItem
	0, // 2: stocks.StockService.AddStock:input_type -> stocks.AddStockRequest
	2, // 3: stocks.StockService.DeleteStock:input_type -> stocks.DeleteStockRequest
	5, // 4: stocks.StockService.ListStocksByLocation:input_type -> stocks.ListStocksByLocationRequest
	7, // 5: stocks.StockService.GetStock:input_type -> stocks.GetStockRequest
	1, // 6: stocks.StockService.AddStock:output_type -> stocks.AddStockResponse
	3, // 7: stocks.StockService.DeleteStock:output_type -> stocks.DeleteStockResponse
	6, // 8: stocks.StockService.ListStocksByLocation:output_type -> stocks.ListStocksByLocationResponse
	8, // 9: stocks.StockService.GetStock:output_type -> stocks.GetStockResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stocks_stocks_proto_init() }
func file_stocks_stocks_proto_init() {
	if File_stocks_stocks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stocks_stocks_proto_rawDesc), len(file_stocks_stocks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stocks_stocks_proto_goTypes,
		DependencyIndexes: file_stocks_stocks_proto_depIdxs,
		MessageInfos:      file_stocks_stocks_proto_msgTypes,
	}.Build()
	File_stocks_stocks_proto = out.File
	file_stocks_stocks_proto_goTypes = nil
	file_stocks_stocks_proto_depIdxs = nil
}
